### ISSUE TITLE
Error while parsing [anime] movie

### ISSUE THREAD

**Issue by avluis** [Benni-chan/nzbToAniDB#23]
Got this error today after updating to the newest build with movie support:

Hashed: ed2k://|file|/volume1/downloads/completed/anime/[Commie] Gurren Lagann The Movie - Childhood's End [BD 1080p FLAC] [55A4A935].mkv|7991720156|a4fed4c3c64975ec96219375153435e7|
Identified: [Commie] Gekijouban Tengen Toppa Gurren Lagann: Gurren-hen (Gurren Lagann the Movie -Childhood`s End-) - 1 -  (Complete Movie)
Renaming to: Gekijouban Tengen Toppa Gurren Lagann Gurren-hen - 01 - [Commie][Blu-ray](1920x1080)(55A4A935).mkv
Traceback (most recent call last):
  File "/volume1/auto/nzbToAniDB/nzbToAniDB.libs/anidb.py", line 408, in <module>
    if (options.directorymovie and info['type'] == 'Movie' and not tvdbinfo):
NameError: name 'tvdbinfo' is not defined

Any idea as to what may be causing it?
I am running without any modifications (except for what is required in anidb.cfg.
I wish I was better at python to be able to give a hand at fixing this.

**Comment by gunmantheh** [comment]
found the problem
fix is on the way, will just need Benni to authorise the pull request (https://github.com/Benni-chan/nzbToAniDB/pull/24)

**Comment by avluis** [comment]
@gunmantheh Thank you for working on this so quickly!
